/* Linux compat stub for virtdisk.h */
#pragma once
#ifndef _WIN32
#include "windows.h"

/* Virtual disk access flags */
typedef enum _VIRTUAL_DISK_ACCESS_FLAG {
    VIRTUAL_DISK_ACCESS_NONE      = 0x00000000,
    VIRTUAL_DISK_ACCESS_ATTACH_RO = 0x00010000,
    VIRTUAL_DISK_ACCESS_ATTACH_RW = 0x00020000,
    VIRTUAL_DISK_ACCESS_DETACH    = 0x00040000,
    VIRTUAL_DISK_ACCESS_GET_INFO  = 0x00080000,
    VIRTUAL_DISK_ACCESS_METAOPS   = 0x00100000,
    VIRTUAL_DISK_ACCESS_WRITABLE  = 0x00200000,
    VIRTUAL_DISK_ACCESS_ALL       = 0x003f0000,
    VIRTUAL_DISK_ACCESS_WRITABLE_METAOPS = 0x00320000
} VIRTUAL_DISK_ACCESS_FLAG;

/* Open flags */
typedef enum _OPEN_VIRTUAL_DISK_FLAG {
    OPEN_VIRTUAL_DISK_FLAG_NONE           = 0x00000000,
    OPEN_VIRTUAL_DISK_FLAG_NO_PARENTS     = 0x00000001,
    OPEN_VIRTUAL_DISK_FLAG_BLANK_FILE     = 0x00000002,
    OPEN_VIRTUAL_DISK_FLAG_BOOT_DRIVE     = 0x00000004,
    OPEN_VIRTUAL_DISK_FLAG_CACHED_IO      = 0x00000008,
    OPEN_VIRTUAL_DISK_FLAG_CUSTOM_DIFF_CHAIN = 0x00000010
} OPEN_VIRTUAL_DISK_FLAG;

/* Virtual storage type */
typedef struct _VIRTUAL_STORAGE_TYPE {
    ULONG DeviceId;
    GUID  VendorId;
} VIRTUAL_STORAGE_TYPE, *PVIRTUAL_STORAGE_TYPE;

#define VIRTUAL_STORAGE_TYPE_DEVICE_UNKNOWN 0
#define VIRTUAL_STORAGE_TYPE_DEVICE_ISO     1
#define VIRTUAL_STORAGE_TYPE_DEVICE_VHD     2
#define VIRTUAL_STORAGE_TYPE_DEVICE_VHDX    3
#define VIRTUAL_STORAGE_TYPE_VENDOR_UNKNOWN {0x00000000,0x0000,0x0000,{0,0,0,0,0,0,0,0}}
#define VIRTUAL_STORAGE_TYPE_VENDOR_MICROSOFT {0xec984aec,0xa0f9,0x47e9,{0x90,0x1f,0x71,0x41,0x5a,0x66,0x34,0x5b}}

/* Create version */
typedef enum _CREATE_VIRTUAL_DISK_VERSION {
    CREATE_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
    CREATE_VIRTUAL_DISK_VERSION_1 = 1,
    CREATE_VIRTUAL_DISK_VERSION_2 = 2
} CREATE_VIRTUAL_DISK_VERSION;

/* Create parameters */
typedef struct _CREATE_VIRTUAL_DISK_PARAMETERS {
    CREATE_VIRTUAL_DISK_VERSION Version;
    union {
        struct { GUID UniqueId; ULONGLONG MaximumSize; ULONG BlockSizeInBytes; ULONG SectorSizeInBytes; PCWSTR ParentPath; PCWSTR SourcePath; } Version1;
        struct { GUID UniqueId; ULONGLONG MaximumSize; ULONG BlockSizeInBytes; ULONG SectorSizeInBytes; ULONG PhysicalSectorSizeInBytes; PCWSTR ParentPath; PCWSTR SourcePath; OPEN_VIRTUAL_DISK_FLAG OpenFlags; VIRTUAL_STORAGE_TYPE ParentVirtualStorageType; VIRTUAL_STORAGE_TYPE SourceVirtualStorageType; } Version2;
    };
} CREATE_VIRTUAL_DISK_PARAMETERS, *PCREATE_VIRTUAL_DISK_PARAMETERS;

/* Create flags */
typedef enum _CREATE_VIRTUAL_DISK_FLAG {
    CREATE_VIRTUAL_DISK_FLAG_NONE              = 0x00000000,
    CREATE_VIRTUAL_DISK_FLAG_FULL_PHYSICAL_ALLOCATION = 0x00000001,
    CREATE_VIRTUAL_DISK_FLAG_PREVENT_WRITES_TO_SOURCE_DISK = 0x00000002,
    CREATE_VIRTUAL_DISK_FLAG_DO_NOT_COPY_METADATA_FROM_PARENT = 0x00000004
} CREATE_VIRTUAL_DISK_FLAG;

/* Open parameters */
typedef enum _OPEN_VIRTUAL_DISK_VERSION {
    OPEN_VIRTUAL_DISK_VERSION_UNSPECIFIED = 0,
    OPEN_VIRTUAL_DISK_VERSION_1 = 1,
    OPEN_VIRTUAL_DISK_VERSION_2 = 2
} OPEN_VIRTUAL_DISK_VERSION;

typedef struct _OPEN_VIRTUAL_DISK_PARAMETERS {
    OPEN_VIRTUAL_DISK_VERSION Version;
    union {
        struct { ULONG RWDepth; } Version1;
        struct { BOOL GetInfoOnly; BOOL ReadOnly; GUID ReadWriteDepth; } Version2;
    };
} OPEN_VIRTUAL_DISK_PARAMETERS, *POPEN_VIRTUAL_DISK_PARAMETERS;

/* Stub API */
static inline DWORD CreateVirtualDisk(PVIRTUAL_STORAGE_TYPE t, PCWSTR p, VIRTUAL_DISK_ACCESS_FLAG a, PSECURITY_DESCRIPTOR sd, CREATE_VIRTUAL_DISK_FLAG f, ULONG pv, PCREATE_VIRTUAL_DISK_PARAMETERS par, LPOVERLAPPED ol, HANDLE* h) { (void)t;(void)p;(void)a;(void)sd;(void)f;(void)pv;(void)par;(void)ol;*h=INVALID_HANDLE_VALUE; return ERROR_CALL_NOT_IMPLEMENTED; }
static inline DWORD OpenVirtualDisk(PVIRTUAL_STORAGE_TYPE t, PCWSTR p, VIRTUAL_DISK_ACCESS_FLAG a, OPEN_VIRTUAL_DISK_FLAG f, POPEN_VIRTUAL_DISK_PARAMETERS par, HANDLE* h) { (void)t;(void)p;(void)a;(void)f;(void)par;*h=INVALID_HANDLE_VALUE; return ERROR_CALL_NOT_IMPLEMENTED; }
static inline DWORD AttachVirtualDisk(HANDLE h, PSECURITY_DESCRIPTOR sd, DWORD f, ULONG pv, PVOID par, LPOVERLAPPED ol) { (void)h;(void)sd;(void)f;(void)pv;(void)par;(void)ol; return ERROR_CALL_NOT_IMPLEMENTED; }
static inline DWORD DetachVirtualDisk(HANDLE h, DWORD f, ULONG pv) { (void)h;(void)f;(void)pv; return ERROR_CALL_NOT_IMPLEMENTED; }
static inline DWORD GetVirtualDiskPhysicalPath(HANDLE h, PULONG sz, PWSTR p) { (void)h;(void)p;if(sz)*sz=0; return ERROR_CALL_NOT_IMPLEMENTED; }

#endif /* !_WIN32 */
